---
# tasks file for send_email
- name: Send an email
  mail:
    host: "{{ smtp_host }}"
    username: "{{ smtp_user }}"
    password: "{{ vault_smtp_pass }}"
    to: "{{ recipients_emails }}"
    from: "aap-dev-noreply@sanofi.com"
    subject: "Test Email"
    body: "This is a test email sent from Ansible."
    secure: try